radanalyticsio/oshinko-cli

pkg/cmd/cli/cmd/create.go
pkg/cmd/cli/cmd/utils.go

The fmt.Errorf() method needs a %s formatter for the
error string. Wrap this in a common util so that we
can report the oshinko base error constant and then
the specific error returned from kube or openshift

Fix error reporting

---

vendor/github.com/radanalyticsio/oshinko-core/clusters/clusters.go

Update oshinko-core in the vendor dir:
This change puts the path of the spark config volume in
UPDATE_SPARK_CONF_DIR instead of SPARK_CONF_DIR in spark
cluster pods. This allows the startup script to check for
presence of the directory and handle it rather than
directly changing where spark looks for it's configuration.

Write path of spark config volume to UPDATE_SPARK_CONF_DIR

---

Makefile
pkg/cmd/cli/cli.go
pkg/cmd/cli/cmd/configmap.go
pkg/cmd/cli/cmd/utils.go
pkg/cmd/cli/extended.go
pkg/cmd/cli/standard.go
scripts/build.sh

The spark application launch scripts need some additional CLI
commands to build and configure a cluster/dirver, but don't need
to include the entire "oc" client. This change adds a build for an
extended oshinko CLI via golang build constraints.

Add a build for an extended utility client

---

pkg/cmd/cli/cmd/create.go
vendor/github.com/radanalyticsio/oshinko-core/clusters/clusterconfigs.go
vendor/github.com/radanalyticsio/oshinko-core/clusters/clusters.go

This change brings oshinko-cli up to date with changes
in oshinko-core to allow the spark image to be specified in
the cluster config. Oshinko-core now treats the "image"
parameter to create() as a default if a cluster config does not
specify an image value. Consequently, the CLI should pass the
default spark image as the "image" parameter and pass any
value from the '--image' flag in a config object.  This
will result in the --image flag value having the highest precedence,
followed by an image value set in a stored config, followed by the
default spark image set in the CLI.
Updates oshinko-core in the vendor dir:
Allow spark image to be specified in clusterconfigs
The create routine already allows the image value to be passed
in as an argument. Allow the image to be set in a cluster …

Pass --image flag value in cluster config object

---

rest/tools/oshinko-client-tests.yaml
rest/tools/oshinko-test.sh

This change updates the paths used by the inline dockerfile and the
oshinko-test.sh script to make sure that the client tests can be run.

update paths for rest client tests

---

rest/tools/common.sh

A path in tools/common.sh needs to be changed after
the merge of oshinko-rest into the rest subdirectory.

Fix oshinko-rest version after merge

---

pkg/cmd/cli/auth/auth.go
test/cmd/get.sh

This is a standard flag but the CLI was not using it. If
this option is passed, the o.Project value will be set
based on the value of this flag instead of from the
list of available projects for the user.

Add support for the --namespace flag

---

core/clusters/clusterconfigs.go
rest/docs/ClusterConfigs.md
rest/tests/unit/clusterconfigs_test.go

The default cluster configuration can optionally be overridden if
a user creates a configmap named default-oshinko-cluster-config in
their project.  Formerly this configmap was named simply "default"
which is far too general.

Change default cluster config map name to default-oshinko-cluster-config

---

cmd/oshinko/oshinko.go

This change enables the kubernetes glog based logging, this will allow
the `--loglevel` flag to be used with the oshinko-cli application.

enable kubernetes logging in oshinko-cli

---

core/clusters/clusterconfigs.go
core/clusters/clusters.go
rest/tests/unit/clusterconfigs_test.go
test/cmd/get.sh

This change is related to recent changes which allow scaling
masters and workers to zero. Creation needs consistency, and
bugs prevented a cluster with master count of zero. Note that
in a cluster created without a master, the workers will loop
forever waiting for the master to be available (ie if/when the
master count is scaled to 1)

Allow creation of clusters with zero masters

---

test/run.sh

'cat /dev/urandom' caused problems on Jenkins

 Use 'date | md5sum' instead of 'cat /dev/urandom' as it hangs on some systems

---

pkg/cmd/cli/cmd/cmd.go
pkg/cmd/cli/cmd/constants.go
pkg/cmd/cli/cmd/create.go
pkg/cmd/cli/cmd/version.go
scripts/build.sh
test/cmd/help.sh
test/cmd/version.sh
version/spark.go

This change allows the default spark image to be set in the build
script. This means that specific releases will be able to vary
the default spark image, and the spark version can be listed
in the release notes.

Set the default spark image to be set at build time

---

rest/HACKING.md
rest/release-templates.sh
rest/tools/oshinko-deploy.sh
rest/tools/release-templates.sh

This change includes a script to generate a server-ui-template.yaml
that references a particular oshinko release. It also modifies
oshinko-deploy.sh so that default image values in the template
are not overwritten unless specificaly specified.

Update HACKING doc and include a script to generate release templates

---

core/clusters/clusterconfigs.go
core/clusters/clusters.go
core/clusters/deploymentconfigs/deploymentconfigs.go
rest/handlers/clusters.go
rest/tests/client/clusters_client_test.go
rest/tests/unit/clusterconfigs_test.go
rest/tools/oshinko-test.sh
test/cmd/create.sh
test/cmd/scale.sh

This change records the spark cluster configuration in an annotation on the spark master deploymentconfig so that complete configuration info can be retrieved on a "get" operation.  The annotation preserves info that cannot be reconstructed easily or at all.   The scale/update operations also modify the annotation to keep it current.

Write cluster config to an annotation on the spark cluster

---

rest/restapi/server.go

The --info flag was read in main.go which is overwritten
by swagger generation. So, test for the --info flag in
in the server startup.

Restore --info flag

---

core/clusters/clusterconfigs.go
core/clusters/clusters.go
pkg/cmd/cli/cmd/cmd.go
pkg/cmd/cli/cmd/create.go
rest/tests/unit/clusterconfigs_test.go
test/cmd/create.sh

This change corresponds to https://github.com/radanalyticsio/openshift-spark/pull/35
It maintains backward compatibility with 'jolokia' as the
default metrics deployment if --metrics is set to 'true' but
also allows the explicit values 'jolokia' and 'prometheus'.
The description also notes that jolokia is deprecated and
prometheus should be used.

Support 'prometheus' as a value for --metrics

---

README.md
scripts/build.sh

This is a PR to solve issue #103 
The build.sh has changed and has been tested on macos and fedora. There is also an additional change to the README.md to help users to build the cli

changes to build for mac and readme

---

scripts/build.sh

There was a problem with the previous implementation (by me) in build.sh for the check for coreutils this has now been changed and is working - a new ticket has been added to in review for the issue to be reviewed

fixed build.sh for mac

---

core/clusters/clusterconfigs.go
test/cmd/create.sh

If a configmap is created to override the default cluster config,
set the "Name" field of the cluster config to default-oshinko-cluster-config
if the configmap is actually read. Otherwise, if hardcoded defaults are used,
set the "Name" field to empty string.

Modify how name of default cluster config is recorded

---

pkg/cmd/cli/cmd/cmd.go
pkg/cmd/cli/cmd/get.go
test/cmd/create.sh
test/cmd/createeph.sh
test/cmd/delete.sh
test/cmd/deleteeph.sh
test/cmd/get.sh
test/cmd/geteph.sh
test/cmd/scale.sh

When using `oshinko get` it will now return the header and results for: name, workers and status

get cli cmd returns headers

---

pkg/cmd/cli/cmd/get.go
test/cmd/get.sh
test/cmd/geteph.sh

If a get tries to get a cluster and there are none it will now return {} if -o json or -o yaml is used to make the output more standardised and what the user asked for rather than an error message. Fixes #45

Returns empty json/yaml for get

---

pkg/cmd/cli/cmd/get.go
pkg/cmd/cli/cmd/utils.go

_output/oshinko get test -o json used to return a json array it now just returns an object
solves issue #46

changed the output for a single cluster to return a json object

---

pkg/cmd/cli/cmd/get.go
test/cmd/get.sh
test/cmd/geteph.sh

This reverts part of the change made in pull request 125 to
return proper empty json/yaml for a cluster list on get. When
a specific cluster is named but is not present, an error should
still be returned

Return an error on get of specific cluster when -o flag is used
